/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cruds;

import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sinyo
 */
public class Form extends javax.swing.JFrame {
    //menampilkan data ke dalam tabel    
    private void tampil(){
        DefaultTableModel model= new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Pekerjaan");
        model.addColumn("Status");
        model.addColumn("Anak");
          try {
            int no=1;
            String sql = "select * from tb_uts_e2_397"; // mengambil data dari tabel
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{
                    no++,
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6)});
        }
            tabel.setModel(model);
        } catch (Exception e) {
        }
     }
    //membersihkan inputan
        private void kosong(){
        tnik.setText(null);
        tnama.setText(null);
        buttonGroup1.getSelection();
        tpekerjaan.setText(null);
        selstatus.setSelectedItem(this);
        tanak.setText(null);
    }

    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("db_uts_e2?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        tbUtsE2397Query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM TbUtsE2397 t");
        tbUtsE2397List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tbUtsE2397Query.getResultList();
        buttonGroup1 = new javax.swing.ButtonGroup();
        tbUtsE2397Query1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM TbUtsE2397 t");
        tbUtsE2397List1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tbUtsE2397Query1.getResultList();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tnik = new javax.swing.JTextField();
        tnama = new javax.swing.JTextField();
        bhapus = new javax.swing.JButton();
        plaki = new javax.swing.JRadioButton();
        bkeluar = new javax.swing.JButton();
        pcewe = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        tanak = new javax.swing.JTextField();
        selstatus = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        tpekerjaan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bsimpan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        bubah = new javax.swing.JButton();
        tpencarian = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel3.setText("NIK");

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel4.setText("Nama");

        tnik.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        tnik.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tnik.setPreferredSize(new java.awt.Dimension(100, 20));

        tnama.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        tnama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tnama.setPreferredSize(new java.awt.Dimension(100, 20));

        bhapus.setBackground(new java.awt.Color(204, 204, 255));
        bhapus.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        bhapus.setIcon(new javax.swing.ImageIcon("C:\\Users\\sinyo\\Documents\\NetBeansProjects\\icon pack\\02_Recycle_24x24.png")); // NOI18N
        bhapus.setText("DELETE");
        bhapus.setPreferredSize(new java.awt.Dimension(130, 40));
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        plaki.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(plaki);
        plaki.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        plaki.setText("Laki - Laki");
        plaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plakiActionPerformed(evt);
            }
        });

        bkeluar.setBackground(new java.awt.Color(204, 204, 255));
        bkeluar.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        bkeluar.setIcon(new javax.swing.ImageIcon("C:\\Users\\sinyo\\Documents\\NetBeansProjects\\icon pack\\logout.png")); // NOI18N
        bkeluar.setText("Log Out");
        bkeluar.setPreferredSize(new java.awt.Dimension(130, 40));

        pcewe.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(pcewe);
        pcewe.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        pcewe.setText("Perempuan");
        pcewe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pceweActionPerformed(evt);
            }
        });

        tabel.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbUtsE2397List1, tabel);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nik}"));
        columnBinding.setColumnName("Nik");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nama}"));
        columnBinding.setColumnName("Nama");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${jenisKelamin}"));
        columnBinding.setColumnName("Jenis Kelamin");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pekerjaan}"));
        columnBinding.setColumnName("Pekerjaan");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${status}"));
        columnBinding.setColumnName("Status");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${anak}"));
        columnBinding.setColumnName("Anak");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        tanak.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        tanak.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tanak.setPreferredSize(new java.awt.Dimension(100, 20));

        selstatus.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        selstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "menikah", "belum menikah", " " }));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        tpekerjaan.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        tpekerjaan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tpekerjaan.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel6.setText("Pekerjaan");

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel7.setText("Status");

        bsimpan.setBackground(new java.awt.Color(204, 204, 255));
        bsimpan.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        bsimpan.setIcon(new javax.swing.ImageIcon("C:\\Users\\sinyo\\Documents\\NetBeansProjects\\icon pack\\04_Save_24x24.png")); // NOI18N
        bsimpan.setText("SAVE");
        bsimpan.setPreferredSize(new java.awt.Dimension(130, 40));
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel8.setText("Anak");

        bubah.setBackground(new java.awt.Color(204, 204, 255));
        bubah.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        bubah.setIcon(new javax.swing.ImageIcon("C:\\Users\\sinyo\\Documents\\NetBeansProjects\\icon pack\\17_Paste_24x24.png")); // NOI18N
        bubah.setText("UPDATE");
        bubah.setPreferredSize(new java.awt.Dimension(130, 40));
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });

        tpencarian.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        tpencarian.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tpencarian.setPreferredSize(new java.awt.Dimension(100, 20));
        tpencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tpencarianKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jLabel1.setText("Pencarian");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(38, 38, 38)
                        .addComponent(plaki)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pcewe)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tnik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tnama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tpekerjaan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selstatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tanak, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tpencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tpencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tnik, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pcewe)
                            .addComponent(plaki)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tpekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(selstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tanak, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // klik 2x pada button hapus untuk menampilkan event action
    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
         // isi fungsi tombol hapus
        try {
            String sql ="delete from tb_uts_e2_397 where nik='"+tnik.getText()+"'"; //query sql
            java.sql.Connection conn=(Connection)config.configDB(); //start  connection
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            //validasi connection
            JOptionPane.showMessageDialog(this, "berhasil di hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil();
        kosong();
    }//GEN-LAST:event_bhapusActionPerformed
    // klik 2x pada button simpan untuk menampilkan event action
    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        //isi fungsi tombol simpan        
        try {
            String sql = "INSERT INTO tb_uts_e2_397 VALUES ('"+tnik.getText()+"','" 
                    +tnama.getText()+"','"+jk+"','"+tpekerjaan.getText()+"','"
                    +selstatus.getSelectedItem()+"','"+tanak.getText()+"')"; //query input data ke dalam database
            java.sql.Connection conn=(Connection)config.configDB(); // start connection
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil"); //validasi insert data
            
            tampil();
            kosong();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_bsimpanActionPerformed
    
    // klik 2x pada radio button
    private void plakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plakiActionPerformed
        jk = "laki-laki"; //isi variabel jk jika pilihan laki-laki
    }//GEN-LAST:event_plakiActionPerformed
    // klik 2x pada radio button
    private void pceweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pceweActionPerformed
        jk = "perempuan"; // isi variabel jk jika piliham perempuan
    }//GEN-LAST:event_pceweActionPerformed
    // klik 2x pada tombol ubah
    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        // isi fungsi tombol ubah
        try {
         String sql ="UPDATE tb_uts_e2_397 SET nama = '"+tnama.getText()+"', nik = '"
                 +tnik.getText()+"', jenis_kelamin = '"+jk+"',pekerjaan= '"
                 +tpekerjaan.getText()+"',status= '"+selstatus.getSelectedItem()+"',anak= '"
                 +tanak.getText()+"' WHERE nik = '"+tnik.getText()+"'"; //query ubah data di database
           java.sql.Connection conn=(Connection)config.configDB(); // start connection
           java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit"); // validasi
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        tampil();
        kosong();

    }//GEN-LAST:event_bubahActionPerformed
    // klik kanan di tabel - event - mouse - mouseclikced
    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
            // select data dengan click data dari tabel        
        int baris = tabel.rowAtPoint(evt.getPoint()); // memasukan data yg di pilih ke form inoutan
        String nik =tabel.getValueAt(baris, 1).toString();
        tnik.setText(nik);
        String nama = tabel.getValueAt(baris,2).toString();
        tnama.setText(nama);
        if ("laki-laki".equals(tabel.getValueAt(baris, 3).toString())) {
            plaki.setSelected(true);
        } else {
            pcewe.setSelected(true);
        };
        String kerja = tabel.getValueAt(baris, 4).toString();
        tpekerjaan.setText(kerja);
        String stat = tabel.getValueAt(baris, 5).toString();
        selstatus.setSelectedItem(stat);
        String anak=tabel.getValueAt(baris, 6).toString();
        tanak.setText(anak);
    }//GEN-LAST:event_tabelMouseClicked
        // klik kanan form- event - window - windowopenned
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampil(); // default method tampil sebagai main layer window
    }//GEN-LAST:event_formWindowOpened
        // klik kanan kolom cari - event - key - keypressed
    private void tpencarianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpencarianKeyPressed
    // fungsi cari per karakter
        DefaultTableModel model= new DefaultTableModel();
        model.addColumn("no");
        model.addColumn("nik");
        model.addColumn("nama");
        model.addColumn("jenis kelamin");
        model.addColumn("pekerjaan");
        model.addColumn("status");
        model.addColumn("anak");
try {
    int no = 1;
    String sql = "select * from tb_uts_e2_397 where nama like '%"
            +tpencarian.getText()+"%' or nik like '%"+tpencarian.getText()+"%'" ; //query memilih data dari kata yg di imput
    java.sql.Connection conn=(Connection)config.configDB();
    java.sql.Statement stm=conn.createStatement();
    java.sql.ResultSet res=stm.executeQuery(sql);
    while(res.next()){
        no++;
        model.addRow(new Object[]{
            no, res.getString("nik"),res.getString("nama"),res.getString("jenis_kelamin"),
            res.getString("pekerjaan"),res.getString("status"),res.getString("anak") }); // menampilkan data yang di dapat ke dalam tabel
            }
            tabel.setModel(model);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } 
    }//GEN-LAST:event_tpencarianKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton pcewe;
    private javax.swing.JRadioButton plaki;
    private javax.swing.JComboBox selstatus;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tanak;
    private java.util.List<cruds.TbUtsE2397> tbUtsE2397List;
    private java.util.List<cruds.TbUtsE2397> tbUtsE2397List1;
    private javax.persistence.Query tbUtsE2397Query;
    private javax.persistence.Query tbUtsE2397Query1;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnik;
    private javax.swing.JTextField tpekerjaan;
    private javax.swing.JTextField tpencarian;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
private String jk; // local variabel untuk menampung data dari radio button

}
